services:
  - type: web
    name: langchain-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: sk-...
      - key: ASTRA_DB_ID
        value: your-id
      - key: ASTRA_DB_APPLICATION_TOKEN
        value: your-token
      - key: ASTRA_DB_REGION
        value: your-region
      - key: ASTRA_DB_KEYSPACE
        value: your-keyspace
